apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: gke-presales
spec:
  base:
    name: default-gke
    version: 1.23.0
  version: v1
  type: custom
  customAddons:
  - name: secrets-store-csi-driver-provider-gcp
    version: v1
  defaultAddons:
    csiSecretStoreConfig:
      providers: {}
    enableCsiSecretStore: true
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        enabled: true
  drift:
    enabled: true
    action: Notify
  opaPolicy:
    enabled: false
  placement:
    autoPublish: true
    fleetValues:
    - gke-presales
  sharing:
    enabled: false
  networkPolicy:
    enabled: false
