apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: gke-presales
spec:
  base:
    name: minimal
    version: 1.27.0
  version: v1
  type: custom
  customAddons:
  - name: ingress-nginx
    version: v1
  defaultAddons:
    csiSecretStoreConfig:
      providers: {}
    enableCsiSecretStore: true
    enableIngress: false
    enableLogging: true
  drift:
    enabled: true
    action: Notify
  opaPolicy:
    enabled: false
  placement:
    autoPublish: true
    fleetValues:
    - gke-presales
  sharing:
    enabled: false
  networkPolicy:
    enabled: false
