apiVersion: config.rafay.dev/v2
kind: ClusterOverride
metadata:
  name: ingress-nginx-lb-ip
spec:
  clusterPlacement:
    placementType: ClusterSpecific
    clusterLabels:
      - key: rafay.dev/clusterName
        value: REPLACE_CLUSTER_NAME
  resourceSelector: rafay.dev/name=ingress-nginx
  type: ClusterOverrideTypeAddon
  overrideValues: |
    commonLabels: 
      env: cs-demo
    controller:
      service:
        # -- Used by cloud providers to connect the resulting `LoadBalancer` to a pre-existing static IP according to https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
        loadBalancerIP: "104.154.136.161"