apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  annotations:
    rafay.dev/description: Google Secret Manager provider for the Secret Store CSI
      Driver. Allows you to access secrets stored in Secret Manager as files mounted
      in Kubernetes pods.
  description: Google Secret Manager provider for the Secret Store CSI Driver. Allows
    you to access secrets stored in Secret Manager as files mounted in Kubernetes
    pods.
  name: secrets-store-csi-driver-provider-gcp
spec:
  agents:
  - {}
  endpoint: https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp
  sharing: {}
  type: Git
