apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: secrets-store-csi-gcp
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: demo-1-gke-1
  resourceQuotas: {}
