apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: eks-presales
spec:
  type: custom
  version: v1
  base:
    name: minimal
  costProfile:
    name: default-cost-profile-aws
    version: 
  defaultAddons:
    csiSecretStoreConfig:
      providers:
        aws: true
    enableCsiSecretStore: true
    enableMonitoring: true
  customAddons:
  - name: autoscaler-addon
    version: v1
  drift:
    action: Notify
    enabled: true
  placement:
    autoPublish: true
    fleetValues:
    - eks-presales
  sharing:
    enabled: false
