kind: Cluster
metadata:
  labels:
    rafay.co/clusterGroup: eks-presales
    k8smgmt.io/fleet: eks-presales
spec:
  blueprint: eks-presales
  blueprintversion: v1
  cloudprovider: aws-demo-credentials
  clusterConfig: null
  cniprovider: aws-cni
  type: eks
---
apiVersion: rafay.io/v1alpha5
kind: ClusterConfig
addons:
- name: aws-ebs-csi-driver
  version: latest
managedNodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 1
  iam:
    withAddonPolicies:
      albIngress: true
      appMesh: false
      autoScaler: true
      efs: false
      externalDNS: true
      imageBuilder: false
  instanceTypes:
  - t3.xlarge
  maxSize: 5
  minSize: 1
  name: default-node-group
  privateNetworking: false
  securityGroups:
    attachIDs: []
  tags: {}
  volumeEncrypted: false
  volumeType: gp3
metadata:
  name: eks-2
  region: us-west-2
  tags:
    email: se-team@rafay.co
    env: cs-demo
    group: presales
  version: "1.26"
vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  nat:
    gateway: Single
  subnets:
    private: {}
    public: {}
