kind: Cluster
metadata:
  labels:
    rafay.co/clusterGroup: eks-presales
    k8smgmt.io/fleet: eks-presales
spec:
  blueprint: eks-presales
  blueprintversion: v1
  cloudprovider: aws-demo-credentials
  clusterConfig: null
  cniprovider: aws-cni
  type: eks
---
apiVersion: rafay.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-2
  region: us-west-2
  tags:
    email: kurt.madel@rafay.co
    env: cs-demo
    group: presales
  version: "1.26"
addons:
- name: aws-ebs-csi-driver
  version: latest
availabilityZones:
- us-west-2a
- us-west-2b
managedNodeGroups:
- name: default-node-group
  amiFamily: AmazonLinux2
  availabilityZones:
  - us-west-2a
  - us-west-2b
  desiredCapacity: 2
  iam:
    withAddonPolicies:
      albIngress: true
      appMesh: false
      autoScaler: true
      efs: false
      externalDNS: true
      imageBuilder: false
  instanceTypes:
  - t3.xlarge
  maxSize: 5
  minSize: 1
  privateNetworking: false
  securityGroups:
    attachIDs: []
  tags: {}
  volumeEncrypted: false
  volumeType: gp3
  preBootstrapCommands:
    - sudo adduser -c "" -m added-user
    - sudo su - newuser
    - mkdir .ssh
    - chmod 700 .ssh
    - touch .ssh/authorized_keys
    - chmod 600 .ssh/authorized_keys
vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  nat:
    gateway: Single
  subnets:
    private: {}
    public: {}
