kind: ClusterTemplateSnapshot
apiVersion: infra.k8smgmt.io/v3
metadata:
  description: ""
  name: v1
  project: api-team
  templateName: eks-cluster-template
parameters:
  blueprint_version:
    default: v1
    override:
      allow: true
    restricted: false
  region:
    default: us-west-2
    override:
      allow: true
      values:
      - us-east-2
      - us-west-2
    restricted: true
  version:
    default: "1.26"
    override:
      allow: true
      values:
      - "1.25"
      - "1.26"
      - "1.27"
    restricted: true
spec:
  blueprint: eks-presales
  blueprintversion: '{{ blueprint_version }}'
  cloudprovider: aws-demo-credentials
  cniprovider: aws-cni
  config:
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          albIngress: false
          appMesh: false
          autoScaler: true
          efs: false
          externalDNS: false
          imageBuilder: false
      instanceTypes:
      - t3.xlarge
      labels: {}
      maxSize: 3
      minSize: 1
      name: default-ng
      privateNetworking: false
      securityGroups:
        attachIDs: []
      tags: {}
      volumeEncrypted: false
      volumeType: gp3
    metadata:
      region: '{{ region }}'
      tags: {}
      version: '{{ version }}'
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
      subnets:
        private: {}
        public: {}
  type: eks
