kind: Cluster
metadata:
  name: demo-1-eks-1
spec:
  blueprint: minimal
  blueprintversion: Latest
  cloudprovider: presales-eks-cluster-provisioning
  cniprovider: aws-cni
  proxyconfig: {}
  type: eks
---
apiVersion: rafay.io/v1alpha5
kind: ClusterConfig
managedNodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 1
  iam:
    withAddonPolicies:
      albIngress: true
      autoScaler: true
      externalDNS: true
  instanceTypes:
  - t3.xlarge
  labels:
    k8smgmt.io/fleet: eks-presales-cluster
  maxSize: 5
  minSize: 1
  name: ng-3a963805
  version: "1.26"
  volumeSize: 80
  volumeType: gp3
metadata:
  name: demo-1-eks-1
  region: us-west-2
  tags:
    email: kurt.madel@rafay.co
    env: cs-demo
    group: presales
  version: "1.26"
vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  nat:
    gateway: Single
