kind: Cluster
metadata:
  labels:
    rafay.co/clusterGroup: eks-presales
    k8smgmt.io/fleet: eks-presales
spec:
  blueprint: eks-presales
  blueprintversion: v1
  cloudprovider: aws-demo-credentials
  clusterConfig: null
  cniprovider: aws-cni
  type: eks
---
apiVersion: rafay.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-2
  region: us-west-2
  tags:
    email: kurt.madel@rafay.co
    env: cs-demo
    group: presales
  version: "1.26"
addons:
- name: aws-ebs-csi-driver
  version: latest
availabilityZones:
- us-west-2a
- us-west-2b
identityMappings:
  arns:
  - arn: arn:aws:iam::679196758854:user/kurt.madel@rafay.co
    group:
    - system:masters
    username: kurt.madel@rafay.co
  - arn: arn:aws:iam::679196758854:user/stuff@rafay.co
    group:
    - system:masters
    username: stuff@rafay.co
managedNodeGroups:
- name: default-node-group
  amiFamily: AmazonLinux2
  availabilityZones:
  - us-west-2a
  - us-west-2b
  desiredCapacity: 2
  iam:
    withAddonPolicies:
      albIngress: true
      appMesh: false
      autoScaler: true
      efs: false
      externalDNS: true
      imageBuilder: false
  instanceTypes:
  - t3.xlarge
  maxSize: 5
  minSize: 1
  privateNetworking: false
  securityGroups:
    attachIDs: []
  tags: {}
  volumeEncrypted: false
  volumeType: gp3
  preBootstrapCommands:
    - sudo adduser -c "" -m ubuntu
    - mkdir /home/ubuntu/.ssh
    - chmod 700 /home/ubuntu/.ssh
    - base64 -d <<< "REPLACE_SSH_PUBLIC_KEY" > /home/ubuntu/.ssh/authorized_keys
    - chmod 600 /home/ubuntu/.ssh/authorized_keys
    - chown -R ubuntu:ubuntu /home/ubuntu/.ssh
vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  nat:
    gateway: Single
  subnets:
    private: {}
    public: {}
