apiVersion: v2
kind: Cluster
metadata:
  labels:
    rafay.co/clusterGroup: eks-presales
    k8smgmt.io/fleet: eks-presales
  description: ""
  name: REPLACE
  project: REPLACE
spec:
  clusterTemplateRef:
    name: eks-cluster-template
    version: v1
  values:
    blueprint_version:
      description: ""
      value: v1
