apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: autoscaler
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterType
      value: eks
  resourceQuotas: {}
  
