apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: echo-team-dev
  project: REPLACE_PROJECT
spec:
  limitRange:
    container: {}
    pod:
      max:
        cpu: 1000m
        memory: 2000Mi
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: REPLACE_CLUSTER_NAME
  resourceQuotas:
    cpuLimits: 4000m
    memoryLimits: 8000Mi