apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: REPLACE_NAMESPACE
  project: REPLACE_PROJECT
  labels:
    shared-gateway-access: "true"
spec:
  limitRange:
    container: {}
    pod:
      max:
        cpu: 1000m
        memory: 2000Mi
      min:
        cpu: 100u
        memory: 200Mi
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: REPLACE_CLUSTER_NAME
  resourceQuotas:
    cpuLimits: 4000m
    memoryLimits: 8000Mi
    pods: "20"
    services: "10"
    storageRequests: 100Gi