apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: echo-app-pipeline
  project: echo-team
spec:
  active: true
  stages:
  - config:
      useRevisionFromWebhookTriggerEvent: true
      workload: echo-app
    name: deploy-echo-app
    type: DeployWorkload
  triggers:
  - config:
      repo:
        paths:
        - name: echo.yaml
        provider: Github
        repository: REPLACE_REPO_NAME
        revision: REPLACE_REVISION
    name: echo-app-webhook
    type: Webhook