apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: echo-app
spec:
  artifact:
    artifact:
      paths:
      - name: echo.yaml
      repository: demo-apps
      revision: REPLACE_REVISION
    type: Yaml
  namespace: echo-team-dev
  placement:
    selector: REPLACE_CLUSTER_NAME