apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: echo-app
spec:
  artifact:
    artifact:
      paths:
      - name: echo.yaml
      repository: demo-apps
      revision: main
    type: Yaml
  namespace: echo-team-dev
  placement:
    selector: rafay.dev/clusterName=api-team-gke-49-demo