apiVersion: infra.k8smgmt.io/v3
kind: FleetPlan
metadata:
  name: eks-upgrade-k8s-plan
  project: api-team
spec:
  agents:
  - name: eks-system-sync
  fleet:
    kind: clusters
    labels:
      k8smgmt.io/fleet: eks-presales
    projects:
    - name: api-team
  operationWorkflow:
    operations:
    - action:
        controlPlaneUpgradeConfig:
          version: "1.26"
        description: upgrade-control-plane
        name: upgrade-control-plane
        type: controlPlaneUpgrade
      name: upgrade-control-plane
      posthooks:
      - containerConfig:
          arguments:
          - --k8s-version=v1.26.8
          image: ctadeu/kubepug:latest
          runner: agent
        description: re-run check depreciated apis
        inject:
        - KUBECONFIG
        name: upgrade-posthook
      prehooks:
      - containerConfig:
          arguments:
          - --k8s-version=v1.26.8
          image: ctadeu/kubepug:latest
          runner: agent
        description: check depreciated apis
        inject:
        - KUBECONFIG
        name: upgrade-prehook
    - action:
        description: upgrade-default-ng
        name: upgrade-default-ng
        nodeGroupsUpgradeConfig:
          names:
          - default-node-group
          version: "1.26"
        type: nodeGroupsUpgrade
      name: upgrade-default-ng
      posthooks:
      - containerConfig:
          arguments:
          - -c
          - kubectl get nodes -o wide
          commands:
          - /bin/sh
          image: alpine/k8s:1.26.5
          runner: agent
        description: recheck-get-all-nodes-linux
        inject:
        - KUBECONFIG
        name: recheck-get-all-nodes-linux
      prehooks:
      - containerConfig:
          arguments:
          - -c
          - kubectl get nodes -o wide
          commands:
          - /bin/sh
          image: alpine/k8s:1.25.12
          runner: agent
        description: get-all-nodes-linux
        inject:
        - KUBECONFIG
        name: get-all-nodes-linux