name: caas-self-service
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      type:
        required: true
        type: string
      rafay-environment:
        required: true
        type: string
      cluster-name:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Type of cluster to provision
        options: 
        - eks
        - gke
      region:
        type: choice
        description: region to provision cluster
        options: 
        - us-west-2
        - us-east-2
      rafay-environment:
        type: choice
        description: Rafay console environment
        options: 
        - prod
        - preview
      cluster-name:
        required: false
        description: Override default cluster name of `{project}-{type}-{github.run_number}`
        type: string

jobs:
  create-cluster:
    environment:
      name: ${{ inputs.rafay-environment }}
    runs-on: ubuntu-latest
    env:
      RCTL_REST_ENDPOINT: ${{ secrets.RCTL_REST_ENDPOINT }}
      RCTL_OPS_ENDPOINT: ${{ secrets.RCTL_OPS_ENDPOINT }}
      RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
      RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
      RCTL_PROJECT: caas
      CLUSTER_TYPE: ${{ inputs.type }}
      CLUSTER_NAME: caas-${{ inputs.type }}-${{ github.run_number }}-demo
      SSH_PUBLC_KEY: ${{ secrets.SSH_PUBLC_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup rctl
      uses: rafay-presales/rctl-setup@main
    - name: cluster-name-from-input
      if: ${{ inputs.cluster-name }}
      env:
        CLUSTER_NAME: ${{ inputs.cluster-name }}
      run: echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV
    - name: create-cluster
      shell: bash
      run: |
        yq e -i "(select(documentIndex == 0) | .metadata.project) = \"$RCTL_PROJECT\"" $CLUSTER_TYPE/cluster.yaml
        yq e -i ".metadata.name = \"$CLUSTER_NAME\"" $CLUSTER_TYPE/cluster.yaml
        ENCODED_SSH_KEY=$(echo $SSH_PUBLC_KEY | base64 -w 0)
        sed -i "s/REPLACE_SSH_PUBLIC_KEY/$ENCODED_SSH_KEY/g" $CLUSTER_TYPE/cluster.yaml
        more $CLUSTER_TYPE/cluster.yaml
        rctl apply -f $CLUSTER_TYPE/cluster.yaml -p $RCTL_PROJECT --wait
