name: create namespace
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      type:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      project:
        description: 'project'
        default: "demo-1"
      type:
        type: choice
        description: Type of cluster to provision
        options: 
        - eks
        - gke

env:
  PROJECT: ${{ github.event.inputs.project || 'demo-1' }}

jobs:
  create-namespace:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup rctl
      uses: rafay-presales/rctl-setup@main
    - name: create-namespace
      env:
        RCTL_REST_ENDPOINT: 'console.rafay.dev'
        RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
        RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
        RCTL_PROJECT: ${{ inputs.project }}
        CLUSTER_TYPE: ${{ inputs.type }}
      run: |
        yq e -i ".metadata.project = \"$RCTL_PROJECT\"" $CLUSTER_TYPE/namespace.yaml
        rctl apply -f $CLUSTER_TYPE/namespace.yaml
      shell: bash
