name: create addon
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      type:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      project:
        description: 'project'
        default: "api-team"
      type:
        type: choice
        description: Type of cluster to provision
        options: 
        - eks
        - gke
jobs:
  create-addon:
    runs-on: ubuntu-latest
    env:
      RCTL_REST_ENDPOINT: 'console.rafay.dev'
      RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
      RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
      RCTL_PROJECT: ${{ inputs.project }}
      CLUSTER_TYPE: ${{ inputs.type }}
      CLUSTER_NAME: ${{ inputs.cluster-name }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Setup rctl
      uses: rafay-presales/rctl-setup@main
    - name: create-addon
      run: |
        yq e -i ".metadata.project = \"$RCTL_PROJECT\"" $CLUSTER_TYPE/addon.yaml
        rctl apply -f $CLUSTER_TYPE/addon.yaml
      shell: bash
    - name: create-cluster-override
      if: ${{ github.event.inputs.type == 'eks' }}
      run: |
        sed -i \"s/REPLACE_CLUSTER_NAME/$CLUSTER_NAME/g\" $CLUSTER_TYPE/cluster-override.yaml
        rctl apply -f $CLUSTER_TYPE/cluster-override.yaml
      shell: bash



      
