name: create cloud credential

on: 
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      type:
        required: true
        type: string
      rafay-environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Type of cluster to provision
        options: 
        - eks
        - gke
      project:
        description: 'project'
        default: "api-team"
      rafay-environment:
        type: choice
        description: Rafay console environment
        options: 
        - prod
        - preview

env:
  PROJECT: ${{ github.event.inputs.project || 'api-team' }}
  CLUSTER_TYPE: ${{ github.event.inputs.type || 'eks' }}
  RAFAY_ENVIRONMENT: ${{ inputs.rafay-environment || 'prod' }}

jobs:
  init-env:
    runs-on: ubuntu-latest
    outputs:
      PROJECT: ${{ env.PROJECT }}
      CLUSTER_TYPE: ${{ env.CLUSTER_TYPE }}
      RAFAY_ENVIRONMENT: ${{ env.RAFAY_ENVIRONMENT }}
    steps:
      - run: echo "null"
      
  create-eks-credential:
    if: ${{ needs.init-env.outputs.CLUSTER_TYPE == 'eks' }}
    needs: [init-env]
    uses: rafay-presales/provision-project-demo/.github/workflows/create-eks-credential.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      rafay-environment: ${{  needs.init-env.outputs.RAFAY_ENVIRONMENT }}
      
  create-gke-credential:
    if: ${{ needs.init-env.outputs.CLUSTER_TYPE == 'gke' }}
    needs: [init-env]
    uses: rafay-presales/provision-project-demo/.github/workflows/create-gke-credential.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      rafay-environment: ${{  needs.init-env.outputs.RAFAY_ENVIRONMENT }}
