name: create cluster
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      type:
        required: true
        type: string
      cluster-name:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Type of cluster to provision
        options: 
        - eks
        - gke
      project:
        description: 'project'
        default: "demo-1"
      cluster-name:
        required: false
        description: Override default cluster name of `{project}-{type}-1`
        type: string

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    env:
      RCTL_REST_ENDPOINT: 'console.rafay.dev'
      RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
      RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
      RCTL_PROJECT: ${{ inputs.project }}
      CLUSTER_TYPE: ${{ inputs.type }}
      CLUSTER_NAME: ${{ inputs.project }}-${{ inputs.type }}-1
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup rctl
      uses: rafay-presales/rctl-setup@main
    - name: cluster-name-from-input
      if: ${{ inputs.cluster-name }}
      env:
        CLUSTER_NAME: ${{ inputs.cluster-name }}
      run: echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV
    - name: create-cluster
      run: |
        yq e -i "(select(documentIndex == 0) | .metadata.project) = \"$RCTL_PROJECT\"" $CLUSTER_TYPE/cluster.yaml
        yq e -i ".metadata.name = \"$CLUSTER_NAME\"" $CLUSTER_TYPE/cluster.yaml
        more $CLUSTER_TYPE/cluster.yaml
        rctl apply -f $CLUSTER_TYPE/cluster.yaml -p $RCTL_PROJECT --wait
      shell: bash
