name: create-echo-gitops

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      type:
        required: true
        type: string
      rafay-environment:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Type of cluster to target
        options: 
        - gke
        - eks
      project:
        description: 'new project'
        default: "echo-team"
      share-project:
        description: 'share project'
        default: "shared-infra-team"
      rafay-environment:
        type: choice
        description: Rafay console environment
        options: 
        - prod
        - preview
      cluster-name:
        required: true
        description: Cluster name to deploy system sync agent
        type: string
env:
  PROJECT: ${{ inputs.project || 'echo-team' }}
  SHARE_PROJECT: ${{ inputs.share-project || 'shared-infra-team' }}
  CLUSTER_TYPE: ${{ inputs.type || 'gke' }}
  CLUSTER_NAME: ${{ inputs.cluster-name }}
  RAFAY_ENVIRONMENT: ${{ inputs.rafay-environment || 'prod' }}

jobs:
  create-echo-gitops:
    environment:
      name: ${{ inputs.rafay-environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: echo-gitops-pipeline
    env:
      RCTL_REST_ENDPOINT: ${{ secrets.RCTL_REST_ENDPOINT }}
      RCTL_OPS_ENDPOINT: ${{ secrets.RCTL_OPS_ENDPOINT }}
      RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
      RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
      RCTL_PROJECT: ${{ inputs.project }}
      CLUSTER_TYPE: ${{ inputs.type }}
      CLUSTER_NAME: ${{ inputs.cluster-name }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Generate a GitHub App token
      id: generate_token
      uses: tibdex/github-app-token@v1.8.0
      with:
        app_id: ${{ secrets.PRESALES_GITHUB_APP_ID }}
        private_key: ${{ secrets.PRESALES_GITHUB_APP_KEY }}
    - name: delete-github-repo
      shell: bash
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        gh api \
          --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/rafay-presales/$RCTL_PROJECT
    - name: cluster-name-from-input
      if: ${{ inputs.cluster-name }}
      env:
        CLUSTER_NAME: ${{ inputs.cluster-name }}
      run: echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV
    - name: Setup rctl
      uses: rafay-presales/rctl-setup@main
    - name: create-project
      shell: bash
      run: |
        yq e -i ".metadata.project = \"$RCTL_PROJECT\"" project.yaml
        rctl apply -f project.yaml
    - name: share-cluster
      shell: bash
      run: | 
        rctl share cluster $CLUSTER_NAME --projects $RCTL_PROJECT --project $SHARE_PROJECT --wait
    - name: create-agent
      shell: bash
      run: |
        yq e -i ".metadata.project = \"$RCTL_PROJECT\"" agent.yaml
        yq e -i ".metadata.name = \"$CLUSTER_TYPE-gitops-agent\"" agent.yaml
        yq e -i ".spec.cluster.name = \"$CLUSTER_NAME\"" agent.yaml
        rctl apply -f agent.yaml
    - name: create-namespace
      shell: bash
      run: |
        sed -i "s/REPLACE_CLUSTER_NAME/$CLUSTER_NAME/g" namespace.yaml
        yq e -i ".metadata.project = \"$RCTL_PROJECT\"" namespace.yaml
        yq e -i ".metadata.name = \"$RCTL_PROJECT\"" namespace.yaml
        rctl apply -f namespace.yaml
    - name: create-github-repo
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/rafay-presales/echo-demo-template/generate \
          -f owner='rafay-presales' \
        -f name="$RCTL_PROJECT" \
        -f description='A simple echo demo app manifest.' \
        -F include_all_branches=false \
        -F private=false 
    - name: create-repository
      shell: bash
      run: |
        yq e -i ".metadata.project = \"$RCTL_PROJECT\"" repository.yaml
        yq e -i ".metadata.name = \"$RCTL_PROJECT\"" repository.yaml
        yq e -i ".spec.endpoint = \"https://github.com/rafay-presales/$RCTL_PROJECT.git\"" repository.yaml
        rctl apply -f repository.yaml
    - name: create-workload
      shell: bash
      run: |
        yq e -i ".metadata.project = \"$RCTL_PROJECT\"" workload.yaml
        yq e -i ".metadata.name = \"$RCTL_PROJECT-workload\"" workload.yaml
        yq e -i ".spec.artifact.artifact.repository = \"$RCTL_PROJECT\"" workload.yaml
        yq e -i ".spec.namespace = \"$RCTL_PROJECT\"" workload.yaml
        yq e -i ".spec.placement.selector = \"rafay.dev/clusterName=$CLUSTER_NAME\"" workload.yaml
        rctl apply -f workload.yaml --wait
    - name: create-pipeline
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        yq e -i ".metadata.project = \"$RCTL_PROJECT\"" pipeline.yaml
        yq e -i ".metadata.name = \"$RCTL_PROJECT-pipeline\"" pipeline.yaml
        yq e -i ".spec.triggers[0].name = \"$RCTL_PROJECT-webhook\"" pipeline.yaml
        yq e -i ".spec.triggers[0].repo.repository = \"$RCTL_PROJECT\"" pipeline.yaml
        rctl apply -f pipeline.yaml --wait
        rctl get trigger -p $RCTL_PROJECT $RCTL_PROJECT-webhook -o yaml --v3 > trigger.yaml
        WEBHOOK_URL=$(yq '.triggerstatus.extra.webhook.webhookurl' trigger.yaml)
        WEBHOOK_SECRET=$(yq '.triggerstatus.extra.webhook.webhooksecret' trigger.yaml)
        echo '{"name":"web","active":true,"events":["push","pull_request","release"],"config":{"url":"'"$WEBHOOK_URL"'","secret":"'"$WEBHOOK_SECRET"'","content_type":"form","insecure_ssl":"0"}}' \
          | gh api repos/rafay-presales/$RCTL_PROJECT/hooks --input - -X POST

