name: create project
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      rafay-environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      project:
        required: true
        description: 'Name of Rafay project to create'
        default: "api-team"
        type: string
      rafay-environment:
        type: choice
        description: Rafay console environment
        options: 
        - prod
        - preview
        
jobs:
  create-project:
    environment:
      name: ${{ inputs.rafay-environment }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup rctl
      uses: rafay-presales/rctl-setup@main
    - name: create-project
      env:
        RCTL_REST_ENDPOINT: 'secrets.RCTL_REST_ENDPOINT'
        RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
        RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
        RCTL_PROJECT: ${{ inputs.project }}
      run: rctl create project $RCTL_PROJECT
      shell: bash
