name: create blueprint
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      type:
        required: true
        type: string
      rafay-environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      project:
        description: 'project'
        default: "api-team"
      type:
        type: choice
        description: Type of cluster to provision
        options: 
        - eks
        - gke
      rafay-environment:
        type: choice
        description: Rafay console environment
        options: 
        - prod
        - preview

jobs:
  create-blueprint:
    environment:
      name: ${{ inputs.rafay-environment }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup rctl
      uses: rafay-presales/rctl-setup@main
    - name: create-blueprint
      env:
        RCTL_REST_ENDPOINT: ${{ secrets.RCTL_REST_ENDPOINT }}
        RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
        RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
        RCTL_PROJECT: ${{ inputs.project }}
        CLUSTER_TYPE: ${{ inputs.type }}
        AWS_COST_PROFILE_VERSION: ${{ secrets.AWS_COST_PROFILE_VERSION }}
      run: | 
        yq e -i ".spec.costProfile.version = \"$AWS_COST_PROFILE_VERSION\"" eks/blueprint.yaml
        yq e -i ".metadata.project = \"$RCTL_PROJECT\"" $CLUSTER_TYPE/blueprint.yaml 
        rctl apply -f $CLUSTER_TYPE/blueprint.yaml
      shell: bash
