name: create eks credential
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      project:
        description: 'project'
        default: "demo-1"
jobs:
  create-eks-credential:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup rctl
      uses: rafay-presales/rctl-setup@main
    - name: create-eks-credential
      env:  
        RCTL_REST_ENDPOINT: 'console.rafay.dev'
        RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
        RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
        RCTL_PROJECT: ${{ inputs.project }}
        AWS_CREDENTIAL_ROLE_ARN: ${{ secrets.AWS_CREDENTIAL_ROLE_ARN }}
        AWS_CREDENTIAL_ACCOUNT_ID: ${{ secrets.AWS_CREDENTIAL_ACCOUNT_ID }}
      run: |
        yq e -i ".metadata.project = \"$RCTL_PROJECT\"" eks/credential.yaml
        yq e -i ".spec.credentials.arn = \"$AWS_CREDENTIAL_ROLE_ARN\"" eks/credential.yaml
        yq e -i ".spec.credentials.arn = \"$AWS_CREDENTIAL_ACCOUNT_ID\"" eks/credential.yaml
        rctl apply -f eks/credential.yaml
      shell: bash
