name: delete project
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      type:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Type of cluster to provision
        options: 
        - eks
        - gke
      project:
        description: 'project'
        default: "api-team"

env:
  PROJECT: ${{ github.event.inputs.project || 'api-team' }}
  CLUSTER_TYPE: ${{ github.event.inputs.type || 'eks' }}

jobs:
  delete-project:
    runs-on: ubuntu-latest
    env:
      RCTL_REST_ENDPOINT: 'console.rafay.dev'
      RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
      RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
      RCTL_PROJECT: ${{ inputs.project }}
      CLUSTER_TYPE: ${{ inputs.type }}
    steps:
    - name: Setup rctl
      uses: rafay-presales/rctl-setup@main
    - name: delete-blueprint
      shell: bash
      run: rctl delete blueprint -p $RCTL_PROJECT $CLUSTER_TYPE-presales --v3 --wait
    - name: delete-gke-addon-ns
      shell: bash
      if: ${{ github.event.inputs.type == 'gke' }}
      run: |
        rctl delete addon -p $RCTL_PROJECT secrets-store-csi-driver-provider-gcp --wait
        rctl delete ns -p $RCTL_PROJECT secrets-store-csi-gcp --wait
    - name: delete-eks-addon-ns
      shell: bash
      if: ${{ github.event.inputs.type == 'eks' }}
      run: |
        rctl delete addon -p $RCTL_PROJECT autoscaler-addon --wait
        rctl delete ns -p $RCTL_PROJECT autoscaler --wait
    - name: delete-project
      shell: bash
      run: rctl delete project $RCTL_PROJECT --wait
