name: delete cluster
on:
  schedule:
    # Runs "every day at 10:30 EDT"
    - cron: '30 18 * * 0-6'
  workflow_call:
    inputs:
      project:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      project:
        description: 'project'
        default: "demo-1"

env:
  PROJECT: ${{ github.event.inputs.project || 'demo-1' }}

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Setup rctl
      uses: rafay-presales/rctl-setup@main
    - name: delete-cluster
      env:
        RCTL_REST_ENDPOINT: 'console.rafay.dev'
        RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
        RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
        RCTL_PROJECT: ${{ inputs.project }}
      run: |
        yq e -i ".metadata.project = \"$RCTL_PROJECT\"" gke/cluster.yaml
        yq e -i ".metadata.name = \"$RCTL_PROJECT-gke-1\"" gke/cluster.yaml
        rctl delete -f gke/cluster.yam -y
      shell: bash
