name: delete clusters
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      rafay-environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      project:
        description: 'project to delete all clusters'
        default: "api-team"
      rafay-environment:
        type: choice
        description: Rafay console environment
        options: 
        - prod
        - preview

env:
  PROJECT: ${{ github.event.inputs.project || 'api-team' }}

jobs:
  delete-clusters:
    environment:
      name: ${{ inputs.rafay-environment }}
    runs-on: ubuntu-latest
    steps:
    - name: Setup rctl
      uses: rafay-presales/rctl-setup@main
    - name: delete-clusters
      env:
        RCTL_REST_ENDPOINT: ${{ secrets.RCTL_REST_ENDPOINT }}
        RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
        RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
        RCTL_PROJECT: ${{ inputs.project }}
      run: |
        rctl get clusters --project $RCTL_PROJECT -o yaml > clusters.yaml
        readarray clusters < <(yq e -o=j -I=0 '.[]' clusters.yaml )
        for cluster in "${clusters[@]}"; do
          # identity mapping is a yaml snippet representing a single entry
          CLUSTER_NAME=$(echo "$cluster" | yq e '.name' -)
          echo "cluster name: $CLUSTER_NAME"
          rctl delete cluster $CLUSTER_NAME -y --project $RCTL_PROJECT --wait
        done
        
      shell: bash
