on:
  workflow_dispatch:
    inputs:
      project:
        description: 'project'
        default: "demo-1"
      type:
        type: choice
        description: Type of cluster to provision
        options: 
        - eks
        - gke
jobs:
  demo_app_authentication:
    runs-on: ubuntu-latest
    env:
      CLUSTER_TYPE: ${{ inputs.type }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.PRESALES_GITHUB_APP_ID }}
          private_key: ${{ secrets.PRESALES_GITHUB_APP_KEY }}

      - name: Use the token
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api octocat

      - name: create-sync-repo
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh repo delete rafay-presales/$CLUSTER_TYPE-system-sync --yes

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/rafay-presales/repos \
            -f name="$CLUSTER_TYPE-system-sync" \
            -f description='Repository for Rafay System Sync' \
            -f homepage='https://rafay.co' \
            -F private=false \
            -F has_issues=false \
            -F has_projects=false \
            -F has_wiki=false 
