name: naas-cleanup

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      type:
        required: true
        type: string
      rafay-environment:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      project:
        description: 'project to cleanup naas'
        default: "naas"
      repo-name:
        required: true
        description: 'application repo to delete'
      app-environment:
        type: choice
        description: 'application environment to cleanup'
        options: 
        - dev
        - stage
      rafay-environment:
        type: choice
        description: Rafay console environment
        options: 
        - preview
        - prod
env:
  RCTL_PROJECT: ${{ inputs.project || 'naas' }}
  USER_FIRST_NAME: ${{ inputs.repo-name }}
  REPO_NAME: ${{ inputs.repo-name }}
  APP_ENV: ${{ inputs.app-environment }}
  NAMESPACE_NAME: ${{ inputs.repo-name }}-${{ inputs.app-environment }}
  CLUSTER_NAME: 'shared-infra-team-gke-73-demo'
  RAFAY_ENVIRONMENT: ${{ inputs.rafay-environment || 'preview' }}

jobs:
  cleanup-naas-gitops:
    environment:
      name: ${{ inputs.rafay-environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: echo-gitops-pipeline
    env:
      RCTL_REST_ENDPOINT: ${{ secrets.RCTL_REST_ENDPOINT }}
      RCTL_OPS_ENDPOINT: ${{ secrets.RCTL_OPS_ENDPOINT }}
      RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
      RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Generate a GitHub App token
      id: generate_token
      uses: tibdex/github-app-token@v1.8.0
      with:
        app_id: ${{ secrets.PRESALES_GITHUB_APP_ID }}
        private_key: ${{ secrets.PRESALES_GITHUB_APP_KEY }}
    - name: delete-github-repo
      shell: bash
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        gh api \
          --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/rafay-presales/$REPO_NAME
    - name: Setup rctl
      uses: rafay-presales/rctl-setup@main
    - name: delete-user-group
      shell: bash
      continue-on-error: true
      run: |
        rctl delete group $RCTL_PROJECT-$NAMESPACE_NAME
    - name: delete-agent
      shell: bash
      run: |
        rctl delete agent $NAMESPACE_NAME-gitops-agent -p $RCTL_PROJECT
    - name: delete-pipeline
      shell: bash
      run: |
        rctl delete pipeline $NAMESPACE_NAME-pipeline -p $RCTL_PROJECT
    - name: delete-workload
      shell: bash
      run: |
        rctl delete workload $NAMESPACE_NAME-workload -p $RCTL_PROJECT --v3
    - name: delete-namespace
      shell: bash
      run: |
        rctl delete namespace $NAMESPACE_NAME -p $RCTL_PROJECT
    - name: delete-repository
      shell: bash
      run: |
        rctl delete repository $REPO_NAME -p $RCTL_PROJECT
