name: naas-cleanup

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'project to cleanup naas'
        default: "naas"
      repo-name:
        required: true
        description: 'application repo to delete'
      rafay-environment:
        type: choice
        description: rafay console environment
        options: 
        - preview
        - prod
      delete-user:
        type: boolean
        description: 'set to true to delete naas user'
        default: false
env:
  RCTL_PROJECT: ${{ inputs.project || 'naas' }}
  USER_FIRST_NAME: ${{ inputs.repo-name }}
  DELETE_USER: ${{ inputs.delete-user }}
  REPO_NAME: ${{ inputs.repo-name }}
  NAMESPACE_NAME_PREFIX: ${{ inputs.repo-name }}
  CLUSTER_NAME: 'shared-infra-team-gke-73-demo'
  RAFAY_ENVIRONMENT: ${{ inputs.rafay-environment || 'preview' }}

jobs:
  cleanup-naas:
    environment:
      name: ${{ inputs.rafay-environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: echo-gitops-pipeline
    env:
      RCTL_REST_ENDPOINT: ${{ secrets.RCTL_REST_ENDPOINT }}
      RCTL_OPS_ENDPOINT: ${{ secrets.RCTL_OPS_ENDPOINT }}
      RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
      RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Generate a GitHub App token
      id: generate_token
      uses: tibdex/github-app-token@v1.8.0
      with:
        app_id: ${{ secrets.PRESALES_GITHUB_APP_ID }}
        private_key: ${{ secrets.PRESALES_GITHUB_APP_KEY }}
    - name: delete-github-repo
      shell: bash
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        gh api \
          --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/rafay-presales/$REPO_NAME
    - name: Setup rctl
      uses: rafay-presales/rctl-setup@main
    - name: delete-user-group
      shell: bash
      run: |
        rctl delete group $RCTL_PROJECT-$NAMESPACE_NAME_PREFIX
    - name: delete-user
      if: ${{ github.env.SYSTEM_SYNC }}
      continue-on-error: true
      shell: bash
      run: |
        rctl delete user kurt.madel+$RCTL_PROJECT-$USER_FIRST_NAME@rafay.co
    - name: delete-agent
      shell: bash
      run: |
        rctl delete agent $NAMESPACE_NAME_PREFIX-gitops-agent -p $RCTL_PROJECT
  cleanup-naas-matrix:
    needs: cleanup-naas
    environment:
      name: ${{ inputs.rafay-environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-env: [dev,stage]
    defaults:
      run:
        working-directory: echo-gitops-pipeline
    env:
      RCTL_REST_ENDPOINT: ${{ secrets.RCTL_REST_ENDPOINT }}
      RCTL_OPS_ENDPOINT: ${{ secrets.RCTL_OPS_ENDPOINT }}
      RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
      RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Generate a GitHub App token
      id: generate_token
      uses: tibdex/github-app-token@v1.8.0
      with:
        app_id: ${{ secrets.PRESALES_GITHUB_APP_ID }}
        private_key: ${{ secrets.PRESALES_GITHUB_APP_KEY }}
    - name: Setup rctl
      uses: rafay-presales/rctl-setup@main
    - name: delete-pipeline
      shell: bash
      run: |
        rctl delete pipeline $NAMESPACE_NAME_PREFIX-${{ matrix.app-env }}-pipeline -p $RCTL_PROJECT
    - name: delete-workload
      shell: bash
      run: |
        rctl delete workload $NAMESPACE_NAME_PREFIX-${{ matrix.app-env }}-workload -p $RCTL_PROJECT --v3
    - name: delete-namespace
      shell: bash
      run: |
        rctl delete namespace $NAMESPACE_NAME_PREFIX-${{ matrix.app-env }} -p $RCTL_PROJECT
    - name: delete-repository
      continue-on-error: true
      shell: bash
      run: |
        rctl delete repository $REPO_NAME -p $RCTL_PROJECT
