name: provision demo project

on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
    paths:
      - '**.yaml'
  schedule:
    # Runs "Mon-Fri at 07:10 EDT"
    - cron: '10 11 * * 1-5' 
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Type of cluster to provision
        options: 
        - gke
        - eks
      project:
        description: 'Name of Rafay project to create'
        default: "api-team"
      rafay-environment:
        type: choice
        description: Rafay console environment
        options: 
        - prod
        - preview
      system-sync:
        type: boolean
        description: 'Include System Sync'
        default: false
      recreate-sync-repo:
        type: boolean
        description: 'Recreate System Sync Repository - will delete all contents'
        default: true

env:
  PROJECT: ${{ github.event.inputs.project || 'api-team' }}
  CLUSTER_TYPE: ${{ github.event.inputs.type || 'gke' }}
  SYSTEM_SYNC: ${{ github.event.inputs.system-sync || false }}
  RECREATE_SYNC_REPO: ${{ github.event.inputs.recreate-sync-repo || true }}
  CLUSTER_NAME: ${{ github.event.inputs.project || 'api-team' }}-${{ github.event.inputs.type || 'gke' }}-${{ github.run_number }}-demo
  RAFAY_ENVIRONMENT: ${{ github.event.inputs.rafay-environment || 'prod' }}

jobs:
  init-env:
    runs-on: ubuntu-latest
    outputs:
      PROJECT: ${{ env.PROJECT }}
      CLUSTER_TYPE: ${{ env.CLUSTER_TYPE }}
      RECREATE_SYNC_REPO: ${{ env.RECREATE_SYNC_REPO }}
      CLUSTER_NAME: ${{ env.CLUSTER_NAME }}
      RAFAY_ENVIRONMENT: ${{ env.RAFAY_ENVIRONMENT }}
    steps:
      - run: echo "init-env"
      
  create-project:
    needs: [init-env]
    uses: rafay-presales/provision-project-demo/.github/workflows/create-project.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      rafay-environment: ${{ needs.init-env.outputs.RAFAY_ENVIRONMENT }}
      
  create-repository:
    needs: [init-env,create-project]
    uses: rafay-presales/provision-project-demo/.github/workflows/create-repository.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      type: ${{  needs.init-env.outputs.CLUSTER_TYPE }}
      rafay-environment: ${{ needs.init-env.outputs.RAFAY_ENVIRONMENT }}
      
  create-namespace:
    needs: [init-env,create-project]
    uses: rafay-presales/provision-project-demo/.github/workflows/create-namespace.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      type: ${{  needs.init-env.outputs.CLUSTER_TYPE }}
      rafay-environment: ${{ needs.init-env.outputs.RAFAY_ENVIRONMENT }}
      
  create-addon:
    needs: [init-env,create-repository,create-namespace]
    uses: rafay-presales/provision-project-demo/.github/workflows/create-addon.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      type: ${{  needs.init-env.outputs.CLUSTER_TYPE }}
      cluster-name: ${{  needs.init-env.outputs.CLUSTER_NAME }}
      rafay-environment: ${{ needs.init-env.outputs.RAFAY_ENVIRONMENT }}
      
  create-credential:
    needs: [init-env,create-project]
    uses: rafay-presales/provision-project-demo/.github/workflows/create-credential.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      type: ${{  needs.init-env.outputs.CLUSTER_TYPE }}
      rafay-environment: ${{ needs.init-env.outputs.RAFAY_ENVIRONMENT }}
      
  create-blueprint:
    needs: [init-env,create-addon]
    uses: rafay-presales/provision-project-demo/.github/workflows/create-blueprint.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      type: ${{  needs.init-env.outputs.CLUSTER_TYPE }}
      rafay-environment: ${{ needs.init-env.outputs.RAFAY_ENVIRONMENT }}
      
  create-cluster-template:
    needs: [init-env,create-project]
    uses: rafay-presales/provision-project-demo/.github/workflows/create-cluster-template.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      type: ${{  needs.init-env.outputs.CLUSTER_TYPE }}
      rafay-environment: ${{ needs.init-env.outputs.RAFAY_ENVIRONMENT }}
      
  create-cluster-template-snapshot:
    needs: [init-env,create-cluster-template,create-blueprint,create-credential]
    uses: rafay-presales/provision-project-demo/.github/workflows/create-cluster-template-snapshot.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      type: ${{  needs.init-env.outputs.CLUSTER_TYPE }}
      rafay-environment: ${{ needs.init-env.outputs.RAFAY_ENVIRONMENT }}
      
  create-cluster:
    needs: [init-env,create-cluster-template-snapshot]
    uses: rafay-presales/provision-project-demo/.github/workflows/create-cluster.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      type: ${{  needs.init-env.outputs.CLUSTER_TYPE }}
      cluster-name: ${{  needs.init-env.outputs.CLUSTER_NAME }}
      rafay-environment: ${{ needs.init-env.outputs.RAFAY_ENVIRONMENT }}
      
  system-sync-setup:
    if: ${{ github.env.SYSTEM_SYNC }}
    needs: [init-env,create-cluster]
    uses: rafay-presales/provision-project-demo/.github/workflows/system-sync-setup.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      type: ${{  needs.init-env.outputs.CLUSTER_TYPE }}
      rafay-environment: ${{ needs.init-env.outputs.RAFAY_ENVIRONMENT }}
      cluster-name: ${{  needs.init-env.outputs.CLUSTER_NAME }}
      recreate-sync-repo: ${{  fromJSON(needs.init-env.outputs.RECREATE_SYNC_REPO) }}
