name: rctl config example
on:
  schedule:
    # Runs "at minute 55 past every hour"
    - cron: '55 * * * *' 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
env:
  RCTL_CONFIG: ${{ secrets.RCTL_CONFIG }}
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run script file
      run: |
         chmod +x ./rctl_setup.sh
         ./rctl_setup.sh
      shell: bash
