name: rctl config example
on:
  schedule:
    # Runs "every day at 02:05"
    - cron: '5 2 * * *' 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      project:
        description: 'project'
        default: "defaultproject"
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rafay-presales/rctl-setup@main
    - name: Run script file
      env:
        RCTL_REST_ENDPOINT: 'console.rafay.dev'
        RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
        RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
        RCTL_PROJECT: 'dev-1'
      run: rctl apply -f gke/gke-from-cluster-template.yaml
      shell: bash
