name: rctl config example
on:
  schedule:
    # Runs "at minute 55 past every hour"
    - cron: '55 * * * *' 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      project:
        description: 'project'
        default: "default-project"
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run script file
      env:
        RCTL_CONFIG: ${{ secrets.RCTL_CONFIG }}
        RCTL_REST_ENDPOINT: "console.rafay.dev"
        RCTL_OPS_ENDPOINT: "console.rafay.dev"
        RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
        RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
        RCTL_PROJECT: "defaultproject"
      run: |
         chmod +x ./rctl_setup.sh
         ./rctl_setup.sh
      shell: bash
