name: rctl config example
on:
  schedule:
    # Runs "at minute 55 past every hour"
    - cron: '55 * * * *' 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      project:
        description: 'project'
        default: "defaultproject"
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rafay-presales/rctl-setup@main
    - name: Run script file
      env:
        RCTL_REST_ENDPOINT: 'console.rafay.dev'
        RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
        RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
        RCTL_PROJECT: 'dev-1'
      run: rctl get clusters
      shell: bash
