name: system-sync-setup

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      type:
        required: true
        type: string
      rafay-environment:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
      recreate-sync-repo:
        type: boolean
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Type of cluster to provision
        options: 
        - eks
        - gke
      project:
        description: 'project'
        default: "api-team"
      rafay-environment:
        type: choice
        description: Rafay console environment
        options: 
        - prod
        - preview
      cluster-name:
        required: true
        description: Cluster name to deploy system sync agent
        type: string
      recreate-sync-repo:
        type: boolean
        description: 'Recreate System Sync Repository - will delete all contents of System Syn repository'
        default: true

env:
  PROJECT: ${{ inputs.project || 'api-team' }}
  CLUSTER_TYPE: ${{ inputs.type || 'eks' }}
  CLUSTER_NAME: ${{ inputs.cluster-name }}
  RECREATE_SYNC_REPO: ${{ inputs.recreate-sync-repo || true }}
  RAFAY_ENVIRONMENT: ${{ inputs.rafay-environment || 'prod' }}

jobs:
  init-env:
    runs-on: ubuntu-latest
    outputs:
      PROJECT: ${{ env.PROJECT }}
      RAFAY_ENVIRONMENT: ${{ env.RAFAY_ENVIRONMENT }}
      CLUSTER_TYPE: ${{ env.CLUSTER_TYPE }}
      CLUSTER_NAME: ${{ inputs.cluster-name || env.CLUSTER_NAME }}
      RECREATE_SYNC_REPO: ${{ env.RECREATE_SYNC_REPO }}
    steps:
      - run: echo "null"
      
  create-agent:
    needs: [init-env]
    uses: rafay-presales/provision-project-demo/.github/workflows/create-agent.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      type: ${{  needs.init-env.outputs.CLUSTER_TYPE }}
      rafay-environment: ${{  needs.init-env.outputs.RAFAY_ENVIRONMENT }}
      cluster-name: ${{  needs.init-env.outputs.CLUSTER_NAME }}
      
  create-repo:
    needs: [init-env,create-agent]
    uses: rafay-presales/provision-project-demo/.github/workflows/create-system-sync-repo.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      type: ${{  needs.init-env.outputs.CLUSTER_TYPE }}
      rafay-environment: ${{  needs.init-env.outputs.RAFAY_ENVIRONMENT }}
      
  create-pipeline:
    needs: [init-env,create-repo]
    uses: rafay-presales/provision-project-demo/.github/workflows/create-system-sync-pipeline.yaml@main
    secrets: inherit
    with:
      project: ${{  needs.init-env.outputs.PROJECT }}
      type: ${{  needs.init-env.outputs.CLUSTER_TYPE }}
      rafay-environment: ${{  needs.init-env.outputs.RAFAY_ENVIRONMENT }}
      recreate-sync-repo: ${{  fromJSON(needs.init-env.outputs.RECREATE_SYNC_REPO) }}
